import useMouse from '@react-hook/mouse-position';
import { motion } from "framer-motion"
import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import Link from "next/link"

import { AiFillGithub } from "react-icons/ai";

export default function Home() {

  const size = useWindowSize();
  const ref = React.useRef(null)
  const mouse = useMouse(ref, {
    fps: 60,
    enterDelay: 100,
    leaveDelay: 100,
  })

  console.log((mouse.x / size.width - 0.5) * 200)

  return (
    <div ref={ref} className="h-screen Background">
      <Head>
        <title>Freedom | Planets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="#" />
        <style>
        {`
          @import url('https://fonts.googleapis.com/css2?family=Teko:wght@300;400;500;600;700&display=swap');
          body {
            font-family: 'Teko', sans-serif;
          }
          .Background {
            background-image: url("/bg-planets.jpg");
            background-repeat: no-repeat;
            background-size: cover;
            background-origin: border-box;
            background-position: ${-300 + (mouse.x / size.width - 0.5) * 30}px center;
          }
          @media (max-width: 1024px) {
            .Background {
                background-position: center center;
            }
          }
        `}
      </style>
      </Head>

      {/* Header */}
      <div className="h-[60px] bg-black border border-black border-b-white border-b-2 flex justify-between items-center">
        <div>
          <h1 className="text-white text-2xl ml-[10%]">Freedom|Planets</h1>
        </div>
        <Link href="https://github.com/Benooux34?tab=repositories">
          <div className="mr-[1%] cursor-pointer">
            <AiFillGithub color="white" fontSize={30} />
          </div>
        </Link>
      </div>

      <div className="lg:ml-[10%] lg:mr-[50%] pt-[50px] lg:pt-[10%]">
        <div className="grid text-center lg:text-left">
          <span className="text-white text-7xl lg:text-8xl">Explorez le système solaire</span>
          <span className="text-gray-200 text-2xl">Venez découvrir toutes les planètes du système solaire ! Vous allez pouvoir retrouver les planètes en 3D et des informations importantes sur le système solaire.</span>
        </div>
        <Link href="/planets">
          <div className="text-center lg:text-left">
            <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white text-3xl border border-2 mt-5 px-10 py-3">Visitez !</motion.button>
          </div>
        </Link>
      </div>
    </div>
  )
}


function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: undefined,
    height: undefined,
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      function handleResize() {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      }
    
      window.addEventListener("resize", handleResize);
     
      handleResize();
    
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []); 
  return windowSize;
}