import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';
import { motion } from "framer-motion"
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";

function planets() {
  return (
    <div className="h-screen bg-[url('https://wallpaperbat.com/img/196032-space-wallpaper-free-hd-download-hq.jpg')] bg-cover">
        <Head>
            <title>Freedom | Planets</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="#" />
            <style>
            {`
                @import url('https://fonts.googleapis.com/css2?family=Teko:wght@300;400;500;600;700&display=swap');
                body {
                    font-family: 'Teko', sans-serif;
                }
            `}
        </style>
      </Head>
        <Header />

        <Swiper
            slidesPerView={4}
            spaceBetween={30}
            className="MySwiper h-[80%] mt-10 bg-transparent space-x-5"
        >
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Soleil</span>
                <img className="h-[250px]" src="sun.jpg" alt="" />
                <span className="text-white text-lg p-5">Le Soleil est l'étoile du Système solaire. Dans la classification astronomique, c'est une étoile de type naine jaune d'une masse d'environ 1,989 1 × 1030 kg , composée d'hydrogène (75 % de la masse ou 92...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Mercure</span>
                <img className="h-[230px] mt-2" src="mercure.jpg" alt="" />
                <span className="text-white text-lg p-5">Mercure est la planète la plus proche du Soleil et la moins massive du Système solaireN 1. Son éloignement au Soleil est compris entre 0,31 et 0,47 unité astronomique (soit 46 et 70 millions de kilomètres), ce qui correspond à une...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Venus</span>
                <img className="w-full" src="venus.jpg" alt="" />
                <span className="text-white text-lg p-5">Vénus est la deuxième planète du Système solaire par ordre d'éloignement au Soleil, et la sixième plus grosse aussi bien par la masse que le diamètre. Elle doit son nom à la déesse romaine de l'amour...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Terre</span>
                <img className="h-[250px]" src="terre.jpg" alt="" />
                <span className="text-white text-lg p-5">La Terre est la troisième planète par ordre d'éloignement au Soleil et la cinquième plus grande du Système solaire aussi bien par la masse que par le diamètre. Par ailleurs, elle est le seul objet céleste connu pour abriter la vie...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Mars</span>
                <img className="h-[250px]" src="mars.jpg" alt="" />
                <span className="text-white text-lg p-5">Mars (prononcé en français : /maʁs/) est la quatrième planète du Système solaire par ordre croissant de la distance au Soleil et la deuxième par ordre croissant de la taille et de la masse...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Jupiter</span>
                <img className="h-[250px]" src="jupiter.jpg" alt="" />
                <span className="text-white text-lg p-5">Jupiter est la cinquième planète du Système solaire par ordre d'éloignement au Soleil, et la plus grande par la taille et la masse devant Saturne, qui est comme elle une planète géante gazeuse...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Saturne</span>
                <img className="w-full" src="saturne.jpg" alt="" />
                <span className="text-white text-lg p-5">Saturne est la sixième planète du Système solaire par ordre d'éloignement au Soleil, et la deuxième plus grande par la taille et la masse après Jupiter, qui est comme elle une planète géante gazeuse...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Uranus</span>
                <img className="h-[250px]" src="uranus.jpg" alt="" />
                <span className="text-white text-lg p-5">Uranus est la septième planète du Système solaire par ordre d'éloignement au Soleil. Elle orbite autour de celui-ci à une distance d'environ 19,2 unités astronomiques (2,87 milliards de kilomètres), avec une période...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide className="bg-black border border-white border-2 mx-5 flex flex-col justify-center items-center">
                <span className="text-white text-5xl">Neptune</span>
                <img className="h-[250px]" src="neptune.jpg" alt="" />
                <span className="text-white text-lg p-5">Neptune est la huitième planète par ordre d'éloignement au Soleil et la plus éloignée connue du Système solaire. Elle orbite autour du Soleil à une distance d'environ 30,1 au (4,5 milliards de kilomètres), avec une excentricité orbitale...</span>
                <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white border border-white border-2 px-3 py-2 text-2xl">Explorez !</motion.button>
            </SwiperSlide>
            <SwiperSlide>

            </SwiperSlide>
        </Swiper>

        {/* <div className="h-[75%] m-10 gap-5 flex space-x-5">
            <div className="h-full w-[25%] bg-black effetneon flex flex-col justify-center items-center">
                <div>
                    <span className="text-white text-5xl">Soleil</span>
                </div>
                <div className="">
                    <img className="h-[280px]" src="sun.jpg" alt="" />
                </div>
                <div className="p-5">
                    <span className="text-white text-xl">La Terre est la troisième planète par ordre d'éloignement au Soleil et la cinquième plus grande du Système solaire aussi bien par la masse...</span>
                </div>
                <div>
                    <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white text-3xl border border-white border-2 px-3 py-2">Explorez !</motion.button>
                </div>
            </div>
            <div className="h-full w-[25%] bg-black border border-white border-2 flex flex-col justify-center items-center">
                <div>
                    <span className="text-white text-5xl">Soleil</span>
                </div>
                <div className="">
                    <img className="h-[280px]" src="sun.jpg" alt="" />
                </div>
                <div className="p-5">
                    <span className="text-white text-xl">La Terre est la troisième planète par ordre d'éloignement au Soleil et la cinquième plus grande du Système solaire aussi bien par la masse...</span>
                </div>
                <div>
                    <motion.button whileHover={{scale: 1.1}} whileTap={{scale: 0.95}} className="text-white text-3xl border border-white border-2 px-3 py-2">Explorez !</motion.button>
                </div>
            </div>
        </div> */}

    </div>
  )
}

export default planets
